export const TYPES = {
  GET_COURSES_LIST_REQUEST: 'GET_COURSES_LIST_REQUEST',
  GET_COURSES_LIST_SUCCESS: 'GET_COURSES_LIST_SUCCESS',
  GET_COURSES_LIST_FAILED: 'GET_COURSES_LIST_FAILED',

  GET_COURSES_CURICULUM_REQUEST: 'GET_COURSES_CURICULUM_REQUEST',
  GET_COURSES_CURICULUM_SUCCESS: 'GET_COURSES_CURICULUM_SUCCESS',

  GET_CURICULUM_DETAILS_REQUEST: 'GET_CURICULUM_DETAILS_REQUEST',
  GET_CURICULUM_DETAILS_SUCCESS: 'GET_CURICULUM_SUCCESS',

  GET_REVIEW_LIST_REQUEST: 'GET_REVIEW_LIST_REQUEST',
  GET_REVIEW_LIST_SUCCESS: 'GET_REVIEW_LIST_SUCCESS',
  GET_REVIEW_LIST_FAILED: 'GET_REVIEW_LIST_FAILED',

  GET_LESSONS_LIST_REQUEST: 'GET_LESSONS_LIST_REQUEST',
  GET_LESSONS_LIST_SUCCESS: 'GET_LESSONS_LIST_SUCCESS',
  GET_LESSONS_LIST_FAILED: 'GET_LESSONS_LIST_FAILED',

  GET_CONTENTS_LIST_REQUEST: 'GET_CONTENTS_LIST_REQUEST',
  GET_CONTENTS_LIST_SUCCESS: 'GET_CONTENTS_LIST_SUCCESS',
  GET_CONTENTS_LIST_FAILED: 'GET_CONTENTS_LIST_FAILED',

  GET_DETAILS_LESSONS_LIST_REQUEST: 'GET_DETAILS_LESSONS_LIST_REQUEST',
  GET_DETAILS_LESSONS_LIST_SUCCESS: 'GET_DETAILS_LESSONS_LIST_SUCCESS',
  GET_DETAILS_LESSONS_LIST_FAILED: 'GET_DETAILS_LESSONS_LIST_FAILED',

  ID_GET_TOPIC_REQUEST: 'ID_GET_TOPIC_REQUEST',
  ID_GET_TOPIC_SUCCESS: 'ID_GET_TOPIC_SUCCESS',

  ID_GET_LESSON_REQUEST: 'ID_GET_LESSON_REQUEST',
  ID_GET_LESSON_SUCCESS: 'ID_GET_LESSON_SUCCESS',
};
