export const TYPES = {
  GET_COURSES_LIST_REQUEST: 'GET_COURSES_LIST_REQUEST',
  GET_COURSES_LIST_SUCCESS: 'GET_COURSES_LIST_SUCCESS',
  GET_COURSES_LIST_FAILED: 'GET_COURSES_LIST_FAILED',

  GET_COURSES_CURICULUM_REQUEST: 'GET_COURSES_CURICULUM_REQUEST',
  GET_COURSES_CURICULUM_SUCCESS: 'GET_COURSES_CURICULUM_SUCCESS',

  GET_CURICULUM_DETAILS_REQUEST: 'GET_CURICULUM_DETAILS_REQUEST',
  GET_CURICULUM_DETAILS_SUCCESS: 'GET_CURICULUM_SUCCESS',

  GET_REVIEW_LIST_REQUEST: 'GET_REVIEW_LIST_REQUEST',
  GET_REVIEW_LIST_SUCCESS: 'GET_REVIEW_LIST_SUCCESS',
  GET_REVIEW_LIST_FAILED: 'GET_REVIEW_LIST_FAILED',

  GET_LESSONS_LIST_REQUEST: 'GET_LESSONS_LIST_REQUEST',
  GET_LESSONS_LIST_SUCCESS: 'GET_LESSONS_LIST_SUCCESS',
  GET_LESSONS_LIST_FAILED: 'GET_LESSONS_LIST_FAILED',

  GET_CONTENTS_LIST_REQUEST: 'GET_CONTENTS_LIST_REQUEST',
  GET_CONTENTS_LIST_SUCCESS: 'GET_CONTENTS_LIST_SUCCESS',
  GET_CONTENTS_LIST_FAILED: 'GET_CONTENTS_LIST_FAILED',

  GET_SINGLE_LESSON_REQUEST: 'GET_SINGLE_LESSON_REQUEST',
  GET_SINGLE_LESSON_SUCCESS: 'GET_SINGLE_LESSON_SUCCESS',
  GET_SINGLE_LESSON_FAILED: 'GET_SINGLE_LESSON_FAILED',

  GET_DETAILS_LESSONS_LIST_REQUEST: 'GET_DETAILS_LESSONS_LIST_REQUEST',
  GET_DETAILS_LESSONS_LIST_SUCCESS: 'GET_DETAILS_LESSONS_LIST_SUCCESS',
  GET_DETAILS_LESSONS_LIST_FAILED: 'GET_DETAILS_LESSONS_LIST_FAILED',

  GET_QUIZ_QUESTIONS_REQUEST: 'GET_QUIZ_QUESTIONS_REQUEST',
  GET_QUIZ_QUESTIONS_SUCCESS: 'GET_QUIZ_QUESTIONS_SUCCESS',
  GET_QUIZ_QUESTIONS_FAILED: 'GET_QUIZ_QUESTIONS_FAILED',

  ID_GET_TOPIC_REQUEST: 'ID_GET_TOPIC_REQUEST',
  ID_GET_TOPIC_SUCCESS: 'ID_GET_TOPIC_SUCCESS',

  ID_GET_LESSON_REQUEST: 'ID_GET_LESSON_REQUEST',
  ID_GET_LESSON_SUCCESS: 'ID_GET_LESSON_SUCCESS',

  GET_COURSE_REQUEST: 'GET_COURSE_REQUEST',
  GET_COURSE_SUCCESS: 'GET_COURSE_SUCCESS',
  GET_COURSE_FAILED: 'GET_COURSE_FAILED',

  GET_ALL_COURSES_LIST_REQUEST: 'GET_ALL_COURSES_LIST_REQUEST',
  GET_ALL_COURSES_LIST_SUCCESS: 'GET_ALL_COURSES_LIST_SUCCESS',
  GET_ALL_COURSES_LIST_FAILED: 'GET_ALL_COURSES_LIST_FAILED',

  PUT_UPDATE_COURSE_REQUEST: 'PUT_UPDATE_COURSE_REQUEST',
  PUT_UPDATE_COURSE_SUCCESS: 'PUT_UPDATE_COURSE_SUCCESS',
  PUT_UPDATE_COURSE_FAILED: 'PUT_UPDATE_COURSE_FAILED',

  POST_COURSE_REQUEST: 'POST_COURSE_REQUEST',
  POST_COURSE_SUCCESS: 'POST_COURSE_SUCCESS',
  POST_COURSE_FAILED: 'POST_COURSE_FAILED',

  DELETE_COURSE_REQUEST: 'DELETE_COURSE_REQUEST',
  DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
  DELETE_COURSE_FAILED: 'DELETE_COURSE_FAILED',

  PUT_UPDATE_LESSON_REQUEST: 'PUT_UPDATE_LESSON_REQUEST',
  PUT_UPDATE_LESSON_SUCCESS: 'PUT_UPDATE_LESSON_SUCCESS',
  PUT_UPDATE_LESSON_FAILED: 'PUT_UPDATE_LESSON_FAILED',

  POST_LESSON_REQUEST: 'POST_LESSON_REQUEST',
  POST_LESSON_SUCCESS: 'POST_LESSON_SUCCESS',
  POST_LESSON_FAILED: 'POST_LESSON_FAILED',

  DELETE_LESSON_REQUEST: 'DELETE_LESSON_REQUEST',
  DELETE_LESSON_SUCCESS: 'DELETE_LESSON_SUCCESS',
  DELETE_LESSON_FAILED: 'DELETE_LESSON_FAILED',

  PUT_UPDATE_LESSON_CONTENT_REQUEST: 'PUT_UPDATE_LESSON_CONTENT_REQUEST',
  PUT_UPDATE_LESSON_CONTENT_SUCCESS: 'PUT_UPDATE_LESSON_CONTENT_SUCCESS',
  PUT_UPDATE_LESSON_CONTENT_FAILED: 'PUT_UPDATE_LESSON_CONTENT_FAILED',

  POST_LESSON_CONTENT_REQUEST: 'POST_LESSON_CONTENT_REQUEST',
  POST_LESSON_CONTENT_SUCCESS: 'POST_LESSON_CONTENT_SUCCESS',
  POST_LESSON_CONTENT_FAILED: 'POST_LESSON_CONTENT_FAILED',

  DELETE_LESSON_CONTENT_REQUEST: 'DELETE_LESSON_CONTENT_REQUEST',
  DELETE_LESSON_CONTENT_SUCCESS: 'DELETE_LESSON_CONTENT_SUCCESS',
  DELETE_LESSON_CONTENT_FAILED: 'DELETE_LESSON_CONTENT_FAILED',

  PUT_UPDATE_TOPIC_CONTENT_REQUEST: 'PUT_UPDATE_TOPIC_CONTENT_REQUEST',
  PUT_UPDATE_TOPIC_CONTENT_SUCCESS: 'PUT_UPDATE_TOPIC_CONTENT_SUCCESS',
  PUT_UPDATE_TOPIC_CONTENT_FAILED: 'PUT_UPDATE_TOPIC_CONTENT_FAILED',

  POST_TOPIC_CONTENT_REQUEST: 'POST_TOPIC_CONTENT_REQUEST',
  POST_TOPIC_CONTENT_SUCCESS: 'POST_TOPIC_CONTENT_SUCCESS',
  POST_TOPIC_CONTENT_FAILED: 'POST_TOPIC_CONTENT_FAILED',

  DELETE_TOPIC_CONTENT_REQUEST: 'DELETE_TOPIC_CONTENT_REQUEST',
  DELETE_TOPIC_CONTENT_SUCCESS: 'DELETE_TOPIC_CONTENT_SUCCESS',
  DELETE_TOPIC_CONTENT_FAILED: 'DELETE_TOPIC_CONTENT_FAILED',

  PUT_UPDATE_QUIZ_QUESTION_REQUEST: 'PUT_UPDATE_QUIZ_QUESTION_REQUEST',
  PUT_UPDATE_QUIZ_QUESTION_SUCCESS: 'PUT_UPDATE_QUIZ_QUESTION_SUCCESS',
  PUT_UPDATE_QUIZ_QUESTION_FAILED: 'PUT_UPDATE_QUIZ_QUESTION_FAILED',

  POST_QUIZ_QUESTION_REQUEST: 'POST_QUIZ_QUESTION_REQUEST',
  POST_QUIZ_QUESTION_SUCCESS: 'POST_QUIZ_QUESTION_SUCCESS',
  POST_QUIZ_QUESTION_FAILED: 'POST_QUIZ_QUESTION_FAILED',

  DELETE_QUIZ_QUESTION_REQUEST: 'DELETE_QUIZ_QUESTION_REQUEST',
  DELETE_QUIZ_QUESTION_SUCCESS: 'DELETE_QUIZ_QUESTION_SUCCESS',
  DELETE_QUIZ_QUESTION_FAILED: 'DELETE_QUIZ_QUESTION_FAILED',
};
