export const TYPES = {
    LIST_PAGE_REQUEST: 'LIST_PAGE_REQUEST',
    LIST_PAGE_SUCCESS: 'LIST_PAGE_SUCCESS',
    LIST_PAGE_FAILED: 'LIST_PAGE_FAILED',

    GET_ONE_PAGE_REQUEST: 'GET_ONE_PAGE_REQUEST',
    GET_ONE_PAGE_SUCCESS: 'GET_ONE_PAGE_SUCCESS',
    GET_ONE_PAGE_FAILED: 'GET_ONE_PAGE_FAILED',

    ADD_PAGE_REQUEST: 'ADD_PAGE_REQUEST',
    ADD_PAGE_SUCCESS: 'ADD_PAGE_SUCCESS',
    ADD_PAGE_FAILED: 'ADD_PAGE_FAILED',

    EDIT_PAGE_REQUEST: 'EDIT_PAGE_REQUEST',
    EDIT_PAGE_SUCCESS: 'EDIT_PAGE_SUCCESS',
    EDIT_PAGE_FAILED: 'EDIT_PAGE_FAILED',

    DELETE_PAGE_REQUEST: 'DELETE_PAGE_REQUEST',
    DELETE_PAGE_SUCCESS: 'DELETE_PAGE_SUCCESS',
    DELETE_PAGE_FAILED: 'DELETE_PAGE_FAILED'

}