export const TYPES = {
  LIST_ANNOUNCEMENT_REQUEST: "LIST_ANNOUNCEMENT_REQUEST",
  LIST_ANNOUNCEMENT_SUCCESS: "LIST_ANNOUNCEMENT_SUCCESS",
  LIST_ANNOUNCEMENT_FAILED: "LIST_ANNOUNCEMENT_FAILED",

  POST_ANNOUNCEMENT_REQUEST: "POST_ANNOUNCEMENT_REQUEST",
  POST_ANNOUNCEMENT_SUCCESS: "POST_ANNOUNCEMENT_SUCCESS",
  POST_ANNOUNCEMENT_FAILED: "POST_ANNOUNCEMENT_FAILED",

  GET_ORGANIZATIONS_REQUEST: "GET_ORGANIZATIONS_REQUEST",
  GET_ORGANIZATIONS_SUCCESS: "GET_ORGANIZATIONS_SUCCESS",
  GET_ORGANIZATIONS_FAILED: "GET_ORGANIZATIONS_FAILED",

  DELETE_ANNOUNCEMENT_REQUEST: "DELETE_ANNOUNCEMENT_REQUEST",
  DELETE_ANNOUNCEMENT_SUCCESS: "DELETE_ANNOUNCEMENT_SUCCESS",
  DELETE_ANNOUNCEMENT_FAILED: "DELETE_ANNOUNCEMENT_FAILED",

  PUT_ANNOUNCEMENT_REQUEST: "PUT_ANNOUNCEMENT_REQUEST",
  PUT_ANNOUNCEMENT_SUCCESS: "PUT_ANNOUNCEMENT_SUCCESS",
  PUT_ANNOUNCEMENT_FAILED: "PUT_ANNOUNCEMENT_FAILED",

  LIST_ANNOUNCEMENT_BY_USER_REQUEST: "LIST_ANNOUNCEMENT_BY_USER_REQUEST",
  LIST_ANNOUNCEMENT_BY_USER_SUCCESS: "LIST_ANNOUNCEMENT_BY_USER_SUCCESS",
  LIST_ANNOUNCEMENT_BY_USER_FAILED: "LIST_ANNOUNCEMENT_BY_USER_FAILED",
};
