export const TYPES = {
  LIST_ANNOUNCEMENT_REQUEST: 'LIST_ANNOUNCEMENT_REQUEST',
  LIST_ANNOUNCEMENT_SUCCESS: 'LIST_ANNOUNCEMENT_SUCCESS',
  LIST_ANNOUNCEMENT_FAILED: 'LIST_ANNOUNCEMENT_FAILED',

  LIST_ANNOUNCEMENTS_REQUEST: 'LIST_ANNOUNCEMENTS_REQUEST',
  LIST_ANNOUNCEMENTS_SUCCESS: 'LIST_ANNOUNCEMENTS_SUCCESS',
  LIST_ANNOUNCEMENTS_FAILED: 'LIST_ANNOUNCEMENTS_FAILED',

  CREATE_ANNOUNCEMENTS_REQUEST: 'CREATE_ANNOUNCEMENTS_REQUEST',
  CREATE_ANNOUNCEMENTS_SUCCESS: 'CREATE_ANNOUNCEMENTS_SUCCESS',
  CREATE_ANNOUNCEMENTS_FAILED: 'CREATE_ANNOUNCEMENTS_FAILED',

  LIST_ORGANIZATIONS_REQUEST: 'LIST_ORGANIZATIONS_REQUEST',
  LIST_ORGANIZATIONS_SUCCESS: 'LIST_ORGANIZATIONS_SUCCESS',
  LIST_ORGANIZATIONS_FAILED: 'LIST_ORGANIZATIONS_FAILED'
};
