export const TYPES = {
  LIST_FOLDERS_REQUEST: 'LIST_FOLDERS_REQUEST',
  LIST_FOLDERS_SUCCESS: 'LIST_FOLDERS_SUCCESS',
  LIST_FOLDERS_FAILED: 'LIST_FOLDERS_FAILED',

  LIST_PAGES_REQUEST: 'LIST_PAGES_REQUEST',
  LIST_PAGES_SUCCESS: 'LIST_PAGES_SUCCESS',
  LIST_PAGES_FAILED: 'LIST_PAGES_FAILED',

  GET_ONE_FOLDER_REQUEST: 'GET_ONE_FOLDER_REQUEST',
  GET_ONE_FOLDER_SUCCESS: 'GET_ONE_FOLDER_SUCCESS',
  GET_ONE_FOLDER_FAILED: 'GET_ONE_FOLDER_FAILED',

  GET_ONE_PAGE_REQUEST: 'GET_ONE_PAGE_REQUEST',
  GET_ONE_PAGE_SUCCESS: 'GET_ONE_PAGE_SUCCESS',
  GET_ONE_PAGE_FAILED: 'GET_ONE_PAGE_FAILED',

  GET_PAGE_DETAILS_REQUEST: 'GET_PAGE_DETAILS_REQUEST',
  GET_PAGE_DETAILS_SUCCESS: 'GET_PAGE_DETAILS_SUCCESS',
};
