export const TYPES = {
    POST_ONBOARDING_YOU_REQUEST: 'POST_ONBOARDING_YOU_REQUEST',
    POST_ONBOARDING_YOU_SUCCESS: 'POST_ONBOARDING_YOU_SUCCESS',
    POST_ONBOARDING_YOU_FAILED: 'POST_ONBOARDING_YOU_FAILED',

    POST_CREATIVE_PROVIDER_REQUEST: 'POST_CREATIVE_PROVIDER_REQUEST',
    POST_CREATIVE_PROVIDER_SUCCESS: 'POST_CREATIVE_PROVIDER_SUCCESS',
    POST_CREATIVE_PROVIDER_FAILED: 'POST_CREATIVE_PROVIDER_FAILED',
}