export const TYPES = {
  GET_ONBOARDING_LIST_REQUEST: "GET_ONBOARDING_LIST_REQUEST",
  GET_ONBOARDING_LIST_SUCCESS: "GET_ONBOARDING_LIST_SUCCESS",
  GET_ONBOARDING_LIST_FAILED: "GET_ONBOARDING_LIST_FAILED",

  POST_ONBOARDING_YOU_REQUEST: "POST_ONBOARDING_YOU_REQUEST",
  POST_ONBOARDING_YOU_SUCCESS: "POST_ONBOARDING_YOU_SUCCESS",
  POST_ONBOARDING_YOU_FAILED: "POST_ONBOARDING_YOU_FAILED",

  POST_CREATIVE_PROVIDER_REQUEST: "POST_CREATIVE_PROVIDER_REQUEST",
  POST_CREATIVE_PROVIDER_SUCCESS: "POST_CREATIVE_PROVIDER_SUCCESS",
  POST_CREATIVE_PROVIDER_FAILED: "POST_CREATIVE_PROVIDER_FAILED",

  DELETE_ONBOARDING_REQUEST: "DELETE_ONBOARDING_REQUEST",
  DELETE_ONBOARDING_SUCCESS: "DELETE_ONBOARDING_SUCCESS",
  DELETE_ONBOARDING_FAILED: "DELETE_ONBOARDING_FAILED",

  PUBLISH_ONBOARDING_REQUEST: "PUBLISH_ONBOARDING_REQUEST",
  PUBLISH_ONBOARDING_SUCCESS: "PUBLISH_ONBOARDING_SUCCESS",
  PUBLISH_ONBOARDING_FAILED: "PUBLISH_ONBOARDING_FAILED",

  EDIT_ONBOARDING_REQUEST: "EDIT_ONBOARDING_REQUEST",
  EDIT_ONBOARDING_SUCCESS: "EDIT_ONBOARDING_SUCCESS",
  EDIT_ONBOARDING_FAILED: "EDIT_ONBOARDING_FAILED",

  GET_ONE_ONBOARDING_REQUEST: "GET_ONE_ONBOARDING_REQUEST",
  GET_ONE_ONBOARDING_SUCCESS: "GET_ONE_ONBOARDING_SUCCESS",
  GET_ONE_ONBOARDING_FAILED: "GET_ONE_ONBOARDING_FAILED",
};
