export const TYPES = {
  LIST_FORMS_REQUEST: "LIST_FORMS_REQUEST",
  LIST_FORMS_SUCCESS: "LIST_FORMS_SUCCESS",
  LIST_FORMS_FAILED: "LIST_FORMS_FAILED",

  GET_ONE_FORMS_REQUEST: "GET_ONE_FORMS_REQUEST",
  GET_ONE_FORMS_SUCCESS: "GET_ONE_FORMS_SUCCESS",
  GET_ONE_FORMS_FAILED: "GET_ONE_FORMS_FAILED",

  GET_ALL_RESULTS_REQUEST: "GET_ALL_RESULTS_REQUEST",
  GET_ALL_RESULTS_SUCCESS: "GET_ALL_RESULTS_SUCCESS",
  GET_ALL_RESULTS_FAILED: "GET_ALL_RESULTS_FAILED",

  DELETE_FORMS_REQUEST: "DELETE_FORMS_REQUEST",
  DELETE_FORMS_SUCCESS: "DELETE_FORMS_SUCCESS",
  DELETE_FORMS_FAILED: "DELETE_FORMS_FAILED",

  POST_FORMS_REQUEST: "POST_FORMS_REQUEST",
  POST_FORMS_SUCCESS: "POST_FORMS_SUCCESS",
  POST_FORMS_FAILED: "POST_FORMS_FAILED",

  PUT_FORMS_REQUEST: "PUT_FORMS_REQUEST",
  PUT_FORMS_SUCCESS: "PUT_FORMS_SUCCESS",
  PUT_FORMS_FAILED: "PUT_FORMS_FAILED",
};
