export const TYPES = {
    LIST_FORM_REQUEST: 'LIST_FORM_REQUEST',
    LIST_FORM_SUCCESS: 'LIST_FORM_SUCCESS',
    LIST_FORM_FAILED: 'LIST_FORM_FAILED',

    CREATE_FORM_REQUEST: 'CREATE_FORM_REQUEST',
    CREATE_FORM_SUCCESS: 'CREATE_FORM_SUCCESS',
    CREATE_FORM_FAILED: 'CREATE_FORM_FAILED',

    EDIT_FORM_REQUEST: 'EDIT_FORM_REQUEST',
    EDIT_FORM_SUCCESS: 'EDIT_FORM_SUCCESS',
    EDIT_FORM_FAILED: 'EDIT_FORM_FAILED',

    GET_ONE_FORM_REQUEST: 'GET_ONE_FORM_REQUEST',
    GET_ONE_FORM_SUCCESS: 'GET_ONE_FORM_SUCCESS',
    GET_ONE_FORM_FAILED: 'GET_ONE_FORM_FAILED',

    GET_ALL_FORM_REQUEST: 'GET_ALL_FORM_REQUEST',
    GET_ALL_FORM_SUCCESS: 'GET_ALL_FORM_SUCCESS',
    GET_ALL_FORM_FAILED: 'GET_ALL_FORM_FAILED',

    DELETE_FORM_REQUEST: 'DELETE_FORM_REQUEST',
    DELETE_FORM_SUCCESS: 'DELETE_FORM_SUCCESS',
    DELETE_FORM_FAILED: 'DELETE_FORM_FAILED',

}