export const TYPES = {
  LIST_DEPARTMENT_REQUEST: 'LIST_DEPARTMENT_REQUEST',
  LIST_DEPARTMENT_SUCCESS: 'LIST_DEPARTMENT_SUCCESS',
  LIST_DEPARTMENT_FAILED: 'LIST_DEPARTMENT_FAILED',

  GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
  GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAILED: 'GET_MEMBERS_FAILED',
};
