export const TYPES = {
  LIST_DEPARTMENT_REQUEST: "LIST_DEPARTMENT_REQUEST",
  LIST_DEPARTMENT_SUCCESS: "LIST_DEPARTMENT_SUCCESS",
  LIST_DEPARTMENT_FAILED: "LIST_DEPARTMENT_FAILED",

  GET_MEMBERS_REQUEST: "GET_MEMBERS_REQUEST",
  GET_MEMBERS_SUCCESS: "GET_MEMBERS_SUCCESS",
  GET_MEMBERS_FAILED: "GET_MEMBERS_FAILED",

  POST_ORGANIZATION_REQUEST: "POST_ORGANIZATION_REQUEST",
  POST_ORGANIZATION_SUCCESS: "POST_ORGANIZATION_SUCCESS",
  POST_ORGANIZATION_FAILED: "POST_ORGANIZATION_FAILED",

  PUT_ORGANIZATION_REQUEST: "PUT_ORGANIZATION_REQUEST",
  PUT_ORGANIZATION_SUCCESS: "PUT_ORGANIZATION_SUCCESS",
  PUT_ORGANIZATION_FAILED: "PUT_ORGANIZATION_FAILED",

  DELETE_ORGANIZATION_REQUEST: "DELETE_ORGANIZATION_REQUEST",
  DELETE_ORGANIZATION_SUCCESS: "DELETE_ORGANIZATION_SUCCESS",
  DELETE_ORGANIZATION_FAILED: "DELETE_ORGANIZATION_FAILED",

  POST_ORGANIZATION_MEMBERS_REQUEST: "POST_ORGANIZATION_MEMBERS_REQUEST",
  POST_ORGANIZATION_MEMBERS_SUCCESS: "POST_ORGANIZATION_MEMBERS_SUCCESS",
  POST_ORGANIZATION_MEMBERS_FAILED: "POST_ORGANIZATION_MEMBERS_FAILED",

  PUT_ORGANIZATION_MEMBERS_REQUEST: "PUT_ORGANIZATION_MEMBERS_REQUEST",
  PUT_ORGANIZATION_MEMBERS_SUCCESS: "PUT_ORGANIZATION_MEMBERS_SUCCESS",
  PUT_ORGANIZATION_MEMBERS_FAILED: "PUT_ORGANIZATION_MEMBERS_FAILED",

  DELETE_ORGANIZATION_MEMBERS_REQUEST: "DELETE_ORGANIZATION_MEMBERS_REQUEST",
  DELETE_ORGANIZATION_MEMBERS_SUCCESS: "DELETE_ORGANIZATION_MEMBERS_SUCCESS",
  DELETE_ORGANIZATION_MEMBERS_FAILED: "DELETE_ORGANIZATION_MEMBERS_FAILED",

  GET_ORGANIZATION_DETAILS_REQUEST: "GET_ORGANIZATION_DETAILS_REQUEST",
  GET_ORGANIZATION_DETAILS_SUCCESS: "GET_ORGANIZATION_DETAILS_SUCCESS",
};
