export const TYPES = {
  GET_AUTHENTICATION_REQUEST: 'GET_AUTHENTICATION_REQUEST',
  GET_AUTHENTICATION_SUCCESS: 'GET_AUTHENTICATION_SUCCESS',
  GET_AUTHENTICATION_FAILED: 'GET_AUTHENTICATION_FAILED',

  POST_SIGNUP_REQUEST: 'POST_SIGNUP_REQUEST',
  POST_SIGNUP_SUCCESS: 'POST_SIGNUP_SUCCESS',
  POST_SIGNUP_FAILED: 'POST_SIGNUP_FAILED',

  TOKEN_CHECKER_REQUEST: 'TOKEN_CHECKER_REQUEST',
  TOKEN_CHECKER_SUCCESS: 'TOKEN_CHECKER_SUCCESS',
  TOKEN_CHECKER_FAILED: 'TOKEN_CHECKER_FAILED',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED',

  GET_USER_DETAILS_REQUEST: 'GET_USER_DETAILS_REQUEST',
  GET_USER_DETAILS_SUCCESS: 'GET_USER_DETAILS_SUCCESS',
  GET_USER_DETAILS_FAILED: 'GET_USER_DETAILS_FAILED',

  GET_USER_ALL_DETAILS_REQUEST: 'GET_USER_ALL_DETAILS_REQUEST',
  GET_USER_ALL_DETAILS_SUCCESS: 'GET_USER_ALL_DETAILS_SUCCESS',
  GET_USER_ALL_DETAILS_FAILED: 'GET_USER_ALL_DETAILS_FAILED',

  PATCH_USER_PROFILE_REQUEST: 'PATCH_USER_PROFILE_REQUEST',
  PATCH_USER_PROFILE_SUCCESS: 'PATCH_USER_PROFILE_SUCCESS',
  PATCH_USER_PROFILE_FAILED: 'PATCH_USER_PROFILE_FAILED',

  POST_OTP_REQUEST: 'POST_OTP_REQUEST',
  VERIFY_OTP_REQUEST: 'VERIFY_OTP_REQUEST',
  REGISTER_ACCOUNT_REQUEST: 'REGISTER_ACCOUNT_REQUEST',
  RESET_PASSWORD_OTP_REQUEST: 'RESET_PASSWORD_OTP_REQUEST',
};
