export const DUMMY_DATA = [
  {
    _id: 1,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
  {
    _id: 2,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
  {
    _id: 3,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
  {
    _id: 3,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
  {
    _id: 3,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
  {
    _id: 3,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
  {
    _id: 3,
    name: "sample name",
    email: "sample@gmail.com",
    contact_number: "09061232323",
    position: "staff",
  },
];
