export const TYPES = {
  LIST_DASHBOARD_REQUEST: 'LIST_DASHBOARD_REQUEST',
  LIST_DASHBOARD_SUCCESS: 'LIST_DASHBOARD_SUCCESS',
  LIST_DASHBOARD_FAILED: 'LIST_DASHBOARD_FAILED',

  GET_ONE_DASHBOARD_REQUEST: 'GET_ONE_DASHBOARD_REQUEST',
  GET_ONE_DASHBOARD_SUCCESS: 'GET_ONE_DASHBOARD_SUCCESS',
  GET_ONE_DASHBOARD_FAILED: 'GET_ONE_DASHBOARD_FAILED',
  
  POST_DASHBOARD_REQUEST: 'POST_DASHBOARD_REQUEST',
  POST_DASHBOARD_SUCCESS: 'POST_DASHBOARD_SUCCESS',
  POST_DASHBOARD_FAILED: 'POST_DASHBOARD_FAILED',
  
  PUT_UPDATE_DASHBOARD_REQUEST: 'PUT_UPDATE_DASHBOARD_REQUEST',
  PUT_UPDATE_DASHBOARD_SUCCESS: 'PUT_UPDATE_DASHBOARD_SUCCESS',
  PUT_UPDATE_DASHBOARD_FAILED: 'PUT_UPDATE_DASHBOARD_FAILED',
  
  DELETE_DASHBOARD_REQUEST: 'DELETE_DASHBOARD_REQUEST',
  DELETE_DASHBOARD_SUCCESS: 'DELETE_DASHBOARD_SUCCESS',
  DELETE_DASHBOARD_FAILED: 'DELETE_DASHBOARD_FAILED',
};
