export const TYPES = {
  LIST_DASHBOARD_REQUEST: 'LIST_DASHBOARD_REQUEST',
  LIST_DASHBOARD_SUCCESS: 'LIST_DASHBOARD_SUCCESS',
  LIST_DASHBOARD_FAILED: 'LIST_DASHBOARD_FAILED',

  GET_ONE_DASHBOARD_REQUEST: 'GET_ONE_DASHBOARD_REQUEST',
  GET_ONE_DASHBOARD_SUCCESS: 'GET_ONE_DASHBOARD_SUCCESS',
  GET_ONE_DASHBOARD_FAILED: 'GET_ONE_DASHBOARD_FAILED',
};
